name: Выполнение SSH команд

on:
  workflow_dispatch: # Ручной запуск рабочего процесса
  schedule:
    - cron: "30 0,13 * * *"  # Каждый день в 8:30 и 21:30 по времени Пекина. Внимание: GitHub Actions использует UTC (координированное всемирное время), а не пекинское время.

jobs:
  execute-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Установить SSHPass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Получить ACCOUNTS_JSON
        id: get-accounts
        run: |
          echo "$ACCOUNTS_JSON" > accounts.json
        env:
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
        # Получить переменную ACCOUNTS_JSON из GitHub Secrets и сохранить в файл accounts.json

      - name: Генерация SSH команд
        id: generate-ssh-commands
        run: |
          echo "#!/bin/bash" > sshpass.sh
          while IFS= read -r account; do
            username=$(echo "$account" | jq -r '.username')
            password=$(echo "$account" | jq -r '.password')
            ssh=$(echo "$account" | jq -r '.ssh')
            cat >> sshpass.sh << EOF
          echo "Выполняю для $username@$ssh"
          sshpass -p '$password' ssh -o StrictHostKeyChecking=no $username@$ssh "\
          bash <(curl -s https://raw.githubusercontent.com/xtfree/singbox-for-serv00/main/singbox/check_cron_sb.sh); \
          "
          EOF
          done < <(jq -c '.[]' accounts.json)
          chmod +x sshpass.sh

      - name: Выполнение SSH команд
        run: ./sshpass.sh
